name: scanly
description: Simple and Comprehensive QR Package. Generate or Scan QR Code Via Camera or From Recent and Gallery.
version: 0.0.1+3
homepage: https://github.com/AhmedAbogameel/scanly
repository: https://github.com/AhmedAbogameel/scanly

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  # Get Images paths
  photo_manager: ^2.1.4
  # Scanning QR
  qr_code_scanner: ^1.0.0
  scan: ^1.6.0
  # Get Images form gallery
  image_picker: ^0.8.5+3
  # Generating QR Code
  qr_flutter: ^4.0.0
  # Permission Asker
  request_permission: ^2.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: